config/routes.rb
Rails.application.routes.draw do
  root 'application#home'

  #sessions routes
  get     '/login',   to: 'sessions#signin'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  #shopping_list routes
  resources :shopping_lists, only: [:index, :show, :new, :edit, :create, :update]
  get     '/external_shopping_lists',  to: 'shopping_lists#list_external'
  get     '/group_shopping_lists',  to: 'shopping_lists#group_shopping_lists'
  get     '/list_order_ancient',  to: 'shopping_lists#list_order_ancient'
  get     '/checkout',  to: 'shopping_lists#checkout'
  get     '/external_shopping_lists',  to: 'shopping_lists#list_external'

  #group routes
  resources :groups, only: [:index, :show, :new, :edit, :create, :update]

  #users routes
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  resources :users, only: [ :show, :new, :create] 
  
  #payments routes
  resources :payments, only: [ :create] 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :shopping_lists_groups
  has_many :shopping_lists, -> { distinct }, through: :shopping_lists_groups, dependent: :destroy
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

  validates :name,
            presence: { message: 'Group name must be given' },
            uniqueness: { message: 'Group name already exists' },
            length: { in: 1..30, message: 'Group name length must be between 1 to 30 characters' }

  validates :icon, presence: { message: 'Icon must be given' }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :logged_in_user

  def index
    @groups = Group.all
  end

  def show; end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    @group.icon = params[:icon]

    if @group.save
      redirect_to groups_path, notice: 'Group was successfully created.'
    elsif @group.errors[:icon].present?
      redirect_to new_group_url, notice: @group.errors[:icon].first
    else
      redirect_to new_group_url, notice: @group.errors[:name].first
    end
  end

  def update
    @group.icon = params[:icon]
    if @group.update(group_params)
      redirect_to groups_path, notice: 'Group was successfully updated.'
    elsif @group.errors[:icon].present?
      redirect_to edit_group_url, notice: @group.errors[:icon].first
    else
      redirect_to edit_group_url, notice: @group.errors[:name].first
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div>
  <%= form_with(model: group, local: true) do |form| %>
    <div class="field">
      <div class="form-input">
        <%= form.text_field :name, class: 'form-control font-label-style',placeholder: "Name of the group"  %>
      </div>
    </div>    
    <div class="field check-input-style">
      <br>
      <%= form.label :icon, class: "font-label-style" %>
      <br>
      <div class="check-item-style">
        <%= radio_button_tag(:icon, "fab fa-500px ") %>    
        <i class="fab fa-500px icon-size-group ml-3"></i>
        <br>
      </div>
      <div class="check-item-style">
        <%= radio_button_tag(:icon, "fas fa-american-sign-language-interpreting") %>    
        <i class="fas fa-american-sign-language-interpreting icon-size-group ml-3"></i>
        <br>
      </div>
      <div class="check-item-style">
        <%= radio_button_tag(:icon, "fab fa-accusoft") %>    
        <i class="fab fa-accusoft icon-size-group ml-3"></i>
        <br>
      </div>
         
      <div class="check-item-style">
        <%= radio_button_tag(:icon, "fas fa-anchor") %>    
        <i class="fas fa-anchor icon-size-group ml-3"></i>
        <br>
      </div>
      <div class="check-item-style">
        <%= radio_button_tag(:icon, "fab fa-amilia") %>    
        <i class="fab fa-amilia icon-size-group ml-3"></i>
        <br>
      </div>
      <div class="check-item-style">
        <%= radio_button_tag(:icon, "fas fa-ambulance") %>    
        <i class="fas fa-ambulance icon-size-group ml-3"></i>
        <br>
      </div>
      <div class="check-item-style">
         <%= radio_button_tag(:icon, "fab fa-amazon") %>    
        <i class="fab fa-amazon icon-size-group ml-3"></i>
        <br>
      </div>
      <div class="check-item-style">
        <%= radio_button_tag(:icon, "fab fa-airbnb") %>    
        <i class="fab fa-airbnb icon-size-group ml-3"></i>
        <br>
      </div>
      <div class="check-item-style">
        <%= radio_button_tag(:icon, "fas fa-air-freshener") %>    
        <i class="fas fa-air-freshener icon-size-group ml-3"></i>
        <br>
      </div>
      <div class="check-item-style">
        <%= radio_button_tag(:icon, "fab fa-alipay") %>    
        <i class="fab fa-alipay icon-size-group ml-3"></i>
        <br>
      </div>
      <div class="check-item-style">
        <%= radio_button_tag(:icon, "fas fa-allergies") %>    
        <i class="fas fa-allergies icon-size-group ml-3"></i>
      </div>
    </div>
    <br>
    <div class="actions">      
      <%= form.submit "Save", class: "btn new-shopping_list-button" %>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<% provide(:navbar_page_title, "edit group") %>
<br>
<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<% provide(:navbar_page_title, "all my groups") %>
<div class="options-order">
  <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
  <div><%= link_to 'Most recent', groups_path, class:"btn btn-link link-login-submit" %></div>
  <div><%= link_to 'Most ancient', groups_path, class:"btn btn-link link-login-submit" %></div>
</div>

<br>
<% @groups.each do |group| %>
  <div class="item-shopping_list">
    <div class="icon-shopping_list">
      <%= link_to "<i class='#{ group.icon }'></i>".html_safe,  group_shopping_lists_path(:id => group.id) %>
    </div>
    <div class="content-shopping_list">
      <h2><%= link_to group.name, group %></h2>      
      <h3><%= group.created_at.strftime("%b %d, %Y - %I:%M%p" ).downcase %></h3>
    </div>
    <div class="amount-shopping_list"><%= group.creator.username %></div>
  </div>
<% end %>
<%= button_to "Create new", new_group_path,  :class => "btn new-shopping_list-button", :method => :get %>

app/views/groups/new.html.erb
<% provide(:navbar_page_title, "Add new group") %>
<br>
<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<% provide(:navbar_page_title, "group information") %>
<br><br>
<p class="font-label-style">
  <strong>Name:</strong>
  <%= @group.name %>
</p>
<p class="font-label-style">
  <strong>Icon:</strong>  
  <i class="<%= @group.icon %>"></i> 
</p>
<p class="font-label-style">
  <strong>User:</strong>
  <%= @group.user_id %>
</p>
<br><br>
<%= link_to 'Edit', edit_group_path(@group), class: 'font-label-style link-edit-back' %> 
<%= link_to 'Back', groups_path, class: 'font-label-style link-edit-back' %>