config/routes.rb
Rails.application.routes.draw do
  root 'application#home'

  #sessions routes
  get     '/login',   to: 'sessions#signin'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  #shopping_list routes
  resources :shopping_lists, only: [:index, :show, :new, :edit, :create, :update]
  get     '/external_shopping_lists',  to: 'shopping_lists#list_external'
  get     '/group_shopping_lists',  to: 'shopping_lists#group_shopping_lists'
  get     '/list_order_ancient',  to: 'shopping_lists#list_order_ancient'
  get     '/checkout',  to: 'shopping_lists#checkout'
  get     '/external_shopping_lists',  to: 'shopping_lists#list_external'

  #group routes
  resources :groups, only: [:index, :show, :new, :edit, :create, :update]

  #users routes
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  resources :users, only: [ :show, :new, :create] 
  
  #payments routes
  resources :payments, only: [ :create] 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shopping_lists, foreign_key: :author_id, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :username, presence: { message: 'Username must be given' },
                       length: { in: 4..20, message: 'Username length must be between 4 to 20 characters' },
                       uniqueness: { message: 'Username already exists' },
                       format: { with: /\A[a-zA-Z0-9]+\z/, message: 'Username must be alphanumeric' }

  def all_total_amount
    shopping_lists.where(active: true).sum(:amount)
  end

  def list_shopping_lists_join_groups
    new_list = []
    shopping_lists.includes(:shopping_lists_groups).each do |item|
      new_list << item unless ShoppingListsGroup.find_by(shopping_list_id: item.id).present?
    end
    new_list
  end

  def shopping_lists_order_recent
    shopping_lists.includes(:shopping_lists_groups).order(created_at: :desc).where(active: true)
  end

  def shopping_lists_order_ancient
    shopping_lists.includes(:shopping_lists_groups).order(:created_at).where(active: true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update destroy]

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to shopping_lists_path, notice: 'User was successfully created.'
    else
      redirect_to signup_path, notice: @user.errors[:username].first
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <ul class="login-items">
      <li><h1>Sign up</h1></li>
      <li><%= form.label :username %></li>
      <li><%= form.text_field :username, class: 'form-control' %></li> 
      <li><br></li>
      <li><%= form.submit "Create", class: "btn btn-success" %><%= link_to "Already register?", login_path, class: "sign-up-link" %></li>
      <li><br></li>      
    </ul>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

<br>

<i class="fab fa-facebook-f fa-3x mx-2"></i>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |form| %>  
  <nav class="d-flex justify-content-between  align-items-center nav-top-bar">
    <div class="options">
      <ul class="nav">
        <li class="nav-item">        
          <%= link_to '<i class="fas fa-chevron-left"></i>'.html_safe, root_path, class:"link-back" %>
        </li>  
      </ul>
    </div>
    <h1 class="title-app">REGISTER</h1>
    <div class="login-nav-bar">
      <ul class="nav">
        <li class="nav-item">      
          <%= form.submit "Next", class: "btn btn-link link-login-submit" %>
        </li>      
      </ul>
    </div>
  </nav>

  <ul class="login-items">
    <li><br></li>
    <li><%= form.text_field :username, class: 'form-control',placeholder: "username" %></li>
    <li><br></li>
    
  </ul>
<% end %>

app/views/users/show.html.erb
<h1>Welcome to show users</h1>