config/routes.rb
Rails.application.routes.draw do
  root 'application#home'

  #sessions routes
  get     '/login',   to: 'sessions#signin'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  #shopping_list routes
  resources :shopping_lists, only: [:index, :show, :new, :edit, :create, :update]
  get     '/external_shopping_lists',  to: 'shopping_lists#list_external'
  get     '/group_shopping_lists',  to: 'shopping_lists#group_shopping_lists'
  get     '/list_order_ancient',  to: 'shopping_lists#list_order_ancient'
  get     '/checkout',  to: 'shopping_lists#checkout'
  get     '/external_shopping_lists',  to: 'shopping_lists#list_external'

  #group routes
  resources :groups, only: [:index, :show, :new, :edit, :create, :update]

  #users routes
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  resources :users, only: [ :show, :new, :create] 
  
  #payments routes
  resources :payments, only: [ :create] 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  has_many :shopping_lists_groups, dependent: :destroy
  has_many :groups, -> { distinct }, through: :shopping_lists_groups, dependent: :destroy
  belongs_to :author, class_name: 'User'

  validates :name,
            presence: { message: 'Name must be given' },
            length: { in: 4..30, message: 'Name length must be between 4 to 30 characters' },
            uniqueness: { message: 'Name already exists' }

  validates :amount,
            presence: { message: 'Amount must be given' },
            numericality: { only_integer: true, message: 'Amount must be numeric' }

  def icons?
    return true if shopping_lists_groups.present?
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :logged_in_user
  before_action :set_shopping_list, only: %i[show edit update destroy checkout]
  before_action :set_group, only: %i[group_shopping_lists]
  include ShoppingListsHelper

  def index
    @shopping_lists = current_user.shopping_lists_order_recent
  end

  def list_order_ancient
    @shopping_lists = current_user.shopping_lists_order_ancient
  end

  def list_external
    @shopping_lists = current_user.list_shopping_lists_join_groups
    @total = total_amount_on_external(@shopping_lists)
  end

  def group_shopping_lists
    @shopping_lists = @group.shopping_lists.where(active: true)
    @total = total_amount_on_external(@shopping_lists)
  end

  def show
    @shopping_list
  end

  def checkout
    @payment = Payment.new
  end

  def new
    @groups_added = []
    @shopping_list = ShoppingList.new
    @group = Group.all
  end

  def edit
    @group = Group.includes(:shopping_lists).all
  end

  def create
    @shopping_list = ShoppingList.new(shopping_list_params)
    @shopping_list.author_id = current_user.id
    @shopping_list.active = true
    @groups_ids = params[:shopping_list][:group_ids]

    if @shopping_list.save
      @groups_ids&.each do |prod|
        @shopping_list.groups << Group.find(prod)
      end
      redirect_to shopping_lists_path, notice: 'ShoppingList was successfully created.'
    elsif @shopping_list.errors[:amount].present?
      redirect_to new_shopping_list_url, notice: @shopping_list.errors[:amount].first
    else
      redirect_to new_shopping_list_url, notice: @shopping_list.errors[:name].first
    end
  end

  def update
    @groups_ids = params[:shopping_list][:group_ids]

    if @shopping_list.update(shopping_list_params)
      if !@groups_ids.nil?
        @groups_ids.each do |prod|
          @shopping_list.groups << Group.find(prod)
        end
      else
        ShoppingListsGroup.where(shopping_list_id: params[:id]).destroy_all
      end
      redirect_to shopping_lists_path, notice: 'ShoppingList was successfully udpated.'
    elsif @shopping_list.errors[:amount].present?
      redirect_to edit_shopping_list_url, notice: @shopping_list.errors[:amount].first
    else
      redirect_to edit_shopping_list_url, notice: @shopping_list.errors[:name].first
    end
  end
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
  def total_amount_on_external(shopping_list)
    sum = 0
    shopping_list.each do |lst|
      sum += lst.amount
    end
    sum
  end

  def show_shopping_result
    @shopping_list.icons? ? 'show_content' : 'no_show_content'
  end

  private

  def set_shopping_list
    @shopping_list = ShoppingList.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def shopping_list_params
    params.require(:shopping_list).permit(:name, :amount,
                                          groups_ids: %i[id icon])
  end

  def shopping_icons
    @shopping_list.icons? ? 'this_content' : 'this_other_content'
  end
end

app/views/shopping_lists/_form.html.erb
<div>
  <%= form_with(model: shopping_list, local: true) do |form| %>
    
    <div class="field">
      <div class="form-input">
        <%= form.text_field :name, class: 'form-control font-label-style',placeholder: "Name of the shopping_list"  %>
      </div>
    </div>

    <div class="field">          
      <div class="form-input">
        <%= form.number_field :amount, class: 'form-control font-label-style',placeholder: "amount example:10" %>
      </div>
    </div>
    <br>
    <div><%= form.label :icon, class: "font-label-style" %></div>
    
    <div class="field check-input-style">      
      <% @group.each do |prod| %>      
        <div class="check-item-style">
          <%= check_box_tag "shopping_list[group_ids][#{prod.id}]", prod.id, @shopping_list.group_ids.include?(prod.id)  %>              
          <%= label_tag(:icon, "#{prod.name}", class: "font-label-style") %>
          <i class="<%= prod.icon %> icon-size-group"></i> 
        </div>
      <% end %>
    </div>
    
    <div class="actions">
      <div>        
        
        <%= form.submit "Save", class: "btn new-shopping_list-button" %>
        
      </div>
    </div>
  <% end %>
</div>

app/views/shopping_lists/_no_show_content.html.erb
<td> <i class="fas fa-question-circle"></i> </td>

app/views/shopping_lists/_show_content.html.erb
<td> 
  <% @shopping_list.groups.each do |type| %> 
    <i class="<%= type.icon %>"></i> 
  <% end %>
</td>

app/views/shopping_lists/_this_content.html.erb
<% @shopping_list.groups.each do |type| %>          
  <i class="<%= type.icon %>"></i> 
<% end %>

app/views/shopping_lists/_this_other_content.html.erb
<i class="fas fa-question-circle"></i>

app/views/shopping_lists/checkout.html.erb
<% provide(:navbar_page_title, "Proceed payment") %>
<br>
<%= form_with(model: @payment, local: true) do |form| %>
<div class="checkout-wrapper">

  <p class="font-label-style checkout-items border-bottom pb-5">
    <span>
      <%= render shopping_icons %>               
    </span>
    <%= @shopping_list.name %>
  </p>

  <p class="font-label-style checkout-items">
    <strong>Transaction code:</strong>
    <%= code =  "CODE234723" %>
    
    <%= form.hidden_field :transaction_code, :value => code %>
  </p>

  <p class="font-label-style checkout-items">
    <strong>Date:</strong>
    <%=   Time.zone.now .strftime("%b %d, %Y - %I:%M%p" ).downcase   %>    
  </p>

  <p class="font-label-style checkout-items">
    <strong>Taxes 3%:</strong>
    <%=  number_to_currency(@shopping_list.amount*0.3, precision: 2)  %>
  </p>

  <p class="font-label-style checkout-items border-bottom pb-5">
    <strong>Total Payment:</strong>
    <%= total_payment= number_to_currency(@shopping_list.amount + @shopping_list.amount*0.3, precision: 2)  %>    
    <%= form.hidden_field :amount, :value => @shopping_list.amount + @shopping_list.amount*0.3 %>
    <%= form.hidden_field :shopping_list_id, :value => @shopping_list.id %>
  </p>
  
  <br><br>
</div>

<%= button_to "Pay", shopping_lists_path,  :class => "btn new-shopping_list-button", :method => :get %>

  <% end %>

app/views/shopping_lists/edit.html.erb
<% provide(:navbar_page_title, "edit shopping_lists") %>
<div class="d-flex flex-column">  
  <%= render 'form', shopping_list: @shopping_list %>
</div>    

app/views/shopping_lists/group_shopping_list.html.erb
<% provide(:navbar_page_title, "ShoppingLists by groups") %>

<div class="options-order">
  <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
  <div><%= link_to 'Most recent', groups_path, class:"btn btn-link link-login-submit" %></div>
  <div><%= link_to 'Most ancient', groups_path, class:"btn btn-link link-login-submit" %></div>
</div>
<div class="d-flex justify-content-between align-items-end  gitf-style">
  <div>Gift credit</div>
  <div><%=  number_to_currency(@total, precision: 2)   %></div>
</div>    
<br>

<% @shopping_lists.each do |shopping_list| %>
  <div class="item-shopping_list">
    <div class="icon-shopping_list">
       <% if shopping_list.icons? %>          
            <% shopping_list.groups.each do |t| %> 
              <i class="<%= t.icon %>"></i> 
              <br>
            <% end %>          
        <% else %>
          <i class="fas fa-question-circle"></i>
        <% end%>  
    </div>
    <div class="content-wishlist">
      <h2><%= link_to shopping_list.name, shopping_list %></h2>
      <h3><%= shopping_list.created_at.strftime("%b %d, %Y - %I:%M%p" ).downcase %></h3>
    </div>
    <div class="amount-shopping_list"><%= number_to_currency(shopping_list.amount, precision: 2)  %></div>
  </div>
<% end %>



<%= button_to "New", new_shopping_list_path,  :class => "btn new-shopping_list-button", :method => :get %>

app/views/shopping_lists/group_shopping_lists.html.erb
<% provide(:navbar_page_title, "Shopping_lists by groups") %>

<div class="options-order">
  <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
  <div><%= link_to 'Most recent', groups_path, class:"btn btn-link link-login-submit" %></div>
  <div><%= link_to 'Most ancient', groups_path, class:"btn btn-link link-login-submit" %></div>
</div>
<div class="d-flex justify-content-between align-items-end  gitf-style">
  <div>Gift credit</div>
  <div><%=  number_to_currency(@total, precision: 2)   %></div>
</div>    
<br>

<% @shopping_lists.each do |shopping_list| %>
  <div class="item-shopping_list">
    <div class="icon-shopping_list">
       <% if shopping_list.icons? %>          
            <% shopping_list.groups.each do |type| %> 
              <i class="<%= type.icon %>"></i> 
              <br>
            <% end %>          
        <% else %>
          <i class="fas fa-question-circle"></i>
        <% end%>
    </div>
    <div class="content-shopping_list">
      <h2><%= link_to shopping_list.name, shopping_list %></h2>
      <h3><%= shopping_list.created_at.strftime("%b %d, %Y - %I:%M%p" ).downcase %></h3>
    </div>
    <div class="amount-shopping_list"><%= number_to_currency(shopping_list.amount, precision: 2)  %></div>
    <div class="amount-shopping_list"><%= @group.creator.username %></div>
  </div>
<% end %>



<%= button_to "Create new group", new_shopping_list_path,  :class => "btn new-shopping_list-button", :method => :get %>

app/views/shopping_lists/index.html.erb
<% provide(:navbar_page_title, "all my shopping_lists") %>

<div class="options-order">
  <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
  <div><%= link_to 'Most recent', shopping_lists_path, class:"btn btn-link link-login-submit" %></div>
  <div><%= link_to 'Most ancient', list_order_ancient_path, class:"btn btn-link link-login-submit" %></div>
</div>
<div class="d-flex justify-content-between align-items-end  gitf-style">
  <div>Gift credit</div>
  <div><%=  number_to_currency(current_user.all_total_amount, precision: 2)  %></div>
</div>    
<br>

<% @shopping_lists.each do |shopping_list| %>
  <div class="item-shopping_list">
    <div class="icon-shopping_list">
       <% if shopping_list.icons? %>         
            <% shopping_list.groups.each do |type| %> 
              <i class="<%= type.icon %>"></i> 
              <br>
            <% end %>          
        <% else %>
          <i class="fas fa-question-circle"></i>
          <br>
        <% end%> 
    </div>
    <div class="content-shopping_list">
      <h2><%= link_to shopping_list.name, shopping_list %></h2>
      <h3><%= shopping_list.created_at.strftime("%b %d, %Y - %I:%M%p" ).downcase %></h3>
    </div>
    <div class="amount-shopping_list">
      <%= number_to_currency(shopping_list.amount, precision: 2)  %>
    </div>
    <div class="pay-shopping_list">
      <%= button_to "Checkout", checkout_path(shopping_list.id),  :class => "btn btn-success", :method => :get, params: {id: shopping_list.id} %>
    </div>
  </div>
<% end %>



<%= button_to "Add new", new_shopping_list_path,  :class => "btn new-shopping_list-button", :method => :get %>

app/views/shopping_lists/list_external.html.erb
<% provide(:navbar_page_title, "all my external shopping_lists") %>

<div class="options-order">
  <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
  <div><%= link_to 'Most recent', external_shopping_lists_path, class:"btn btn-link link-login-submit" %></div>
  <div><%= link_to 'Most ancient', external_shopping_lists_path, class:"btn btn-link link-login-submit" %></div>
</div>
<div class="d-flex justify-content-between align-items-end  gitf-style">
  <div>Gift credit</div>
  <div><%=  number_to_currency(@total, precision: 2)   %></div>
</div>    
<br>

<% @shopping_lists.each do |shopping_list| %>
  <div class="item-shopping_list">
    <div class="icon-shopping_list">
       <% if shopping_list.icons? %>           
            <% shopping_list.groups.each do |type| %> 
              <i class="<%= type.icon %>"></i> 
            <% end %>          
        <% else %>
           <i class="fas fa-question-circle"></i> 
        <% end%> 
    </div>
    <div class="content-shopping_list">
      <h2><%= link_to shopping_list.name, shopping_list %></h2>
      <h3><%= shopping_list.created_at.strftime("%b %d, %Y - %I:%M%p" ).downcase %></h3>
    </div>
    <div class="amount-shopping_list"><%= number_to_currency(shopping_list.amount, precision: 2)   %></div>
  </div>
<% end %>

  



<%= button_to "Add new", new_shopping_list_path,  :class => "btn new-shopping_list-button", :method => :get %>

app/views/shopping_lists/list_order_ancient.html.erb
<% provide(:navbar_page_title, "all my shopping_lists") %>

<div class="options-order">
  <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
  <div><%= link_to 'Most recent', shopping_lists_path, class:"btn btn-link link-login-submit" %></div>
  <div><%= link_to 'Most ancient', list_order_ancient_path, class:"btn btn-link link-login-submit" %></div>
</div>
<div class="d-flex justify-content-between align-items-end  gitf-style">
  <div>Gift credit</div>
  <div><%=  number_to_currency(current_user.all_total_amount, precision: 2)   %></div>
</div>    
<br>

<% @shopping_lists.each do |shopping_list| %>
  <div class="item-shopping_list">
    <div class="icon-shopping_list">
       <% if shopping_list.icons? %>          
            <% shopping_list.groups.each do |type| %> 
              <i class="<%= type.icon %>"></i> 
              <br>
            <% end %>          
        <% else %>
          <i class="fas fa-question-circle"></i>
          <br>
        <% end%>  
    </div>
    <div class="content-shopping_list">
      <h2><%= link_to shopping_list.name, shopping_list %></h2>
      <h3><%= shopping_list.created_at.strftime("%b %d, %Y - %I:%M%p" ).downcase %></h3>
    </div>
    <div class="amount-shopping_list"><%= number_to_currency(shopping_list.amount, precision: 2)  %></div>
  </div>
<% end %>



<%= button_to "New", new_shopping_list_path,  :class => "btn new-shopping_list-button", :method => :get %>

app/views/shopping_lists/new.html.erb
<% provide(:navbar_page_title, "add new shopping_lists") %>

<br>
<div class="d-flex flex-column">            
  <%= render 'form', shopping_list: @shopping_list %>
</div>  

app/views/shopping_lists/show.html.erb
<% provide(:navbar_page_title, "shopping_list information") %>
<br><br>
<p class="font-label-style">
  <strong>Name:</strong>
  <%= @shopping_list.name %>
</p>
<p class="font-label-style">
  <strong>Amount:</strong>
  <%= @shopping_list.amount %>
</p>
<p class="font-label-style">
  <strong>Icon:</strong>
  
    <%= render show_shopping_result %>
</p>
<br><br>
<%= link_to 'Edit', edit_shopping_list_path(@shopping_list), class: 'font-label-style link-edit-back' %> |
<%= link_to 'Back', shopping_lists_path, class: 'font-label-style link-edit-back' %>