config/routes.rb
Rails.application.routes.draw do
  root 'application#home'

  #sessions routes
  get     '/login',   to: 'sessions#signin'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  #shopping_list routes
  resources :shopping_lists, only: [:index, :show, :new, :edit, :create, :update]
  get     '/external_shopping_lists',  to: 'shopping_lists#list_external'
  get     '/group_shopping_lists',  to: 'shopping_lists#group_shopping_lists'
  get     '/list_order_ancient',  to: 'shopping_lists#list_order_ancient'
  get     '/checkout',  to: 'shopping_lists#checkout'
  get     '/external_shopping_lists',  to: 'shopping_lists#list_external'

  #group routes
  resources :groups, only: [:index, :show, :new, :edit, :create, :update]

  #users routes
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  resources :users, only: [ :show, :new, :create] 
  
  #payments routes
  resources :payments, only: [ :create] 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<div class="d-flex justify-content-between  align-items-center nav-top-bar">
    <div class="options">
      <ul class="nav">
        <li class="nav-item">        
           
            <div class="menuToggle">
              <input type="checkbox" />
              <span></span>
              <span></span>
              <span></span>
              <ul class="menu">
                  <li><br></li>                  
                  <li class="nav-user-profile icon-profile">
                    <i class="fas fa-user"></i> 
                  </li>
                  <li class="nav-user-profile"> 
                    <%= current_user.username %> 
                  </li>
                  <li><br></li>                           
                  <li> <%= link_to "All my shopping_list", shopping_lists_path, class: "nav-link active", method: 'get' %></li>
                  <li> <%= link_to "All my external shopping_list ", external_shopping_lists_path, class: "nav-link active", method: 'get' %></li>
                  <li> <%= link_to "All groups", groups_path, class: "nav-link active", method: 'get' %></li>
                  <li> <%= link_to "Log out", logout_path, class: "nav-link active", method: 'delete' %></li>
              </ul>
            </div>
          
        </li>  
      </ul>
    </div>
    <h1 class="title-app">  <%= navbar_page_title(yield(:navbar_page_title)) %> </h1>
    <div class="login-nav-bar">
      <ul class="nav">
        <li class="nav-item">  
          
            <%= link_to '<i class="fas fa-search"></i>'.html_safe, shopping_lists_path, class:"link-back-nav-bar" %>
          
        </li>  
      </ul>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupOurTransactions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= login %>              
    <% flash.each do |message_type, message| %>
       <div class="alert alert-info message-style"><%= message %></div>
    <% end %>
    <main class="container-fluid main-wrapper">
      <div class="col-12 content-wrapper">              
        <%= yield %>
      </div>
      <script src="https://kit.fontawesome.com/688a35b1eb.js" crossorigin="anonymous"></script>
    <main>
  </body>
</html>

app/views/layouts/home.html.erb
<section class="row container-home justify-content-md-center">
    <div class="col-12 title-home row justify-content-md-center align-items-center"> 
        <h1 align='center'>Group our ShoppingList</h1>
    </div>
    <div class="col-12 login-home ">
        <%= button_to "SIGN IN", login_path, :class => "btn btn-custom-login", :method => :get %>
        <%= button_to "SIGN UP", signup_path, :class => "btn btn-custom-signup", :method => :get %>
    </div>    
</section>